version: "3.5"

services:

  api-service:
    build: api-service/
    image: api-service:latest
    ports:
      - "8080:8080"

  customer-service:
    build: ./customer-service/
    image: customer-service:latest
    ports:
      - "8081"

  collector:
    image: logzio/otel-collector-traces
    environment:
      - LOGZIO_REGION=${LOGZIO_REGION}
      - LOGZIO_TRACES_TOKEN=${LOGZIO_TRACES_TOKEN}
    ports:
      - "1777:1777"
      - "9411:9411"
      - "9943:9943"
      - "6831:6831"
      - "6832:6832"
      - "14250:14250"
      - "14268:14268"
      - "4317:4317"
      - "55681:55681"
      - "8888:8888"
