spring.main.allow-bean-definition-overriding: true
spring.jpa.hibernate.ddl-auto: create-drop
spring.liquibase.enabled: false
spring.flyway.enabled: false
io.reflectoring.scheduling.enabled: false
logging.level.org.hibernate.SQL: DEBUG